aws_region      = "eu-west-1"
project_name    = "seera-cc"
db_name         = "seera-db"
db_user         = "user"
db_password     = "passw0rd"
ssh_public_key  = "~/.ssh/id_rsa.pub"
ssh_private_key = "~/.ssh/id_rsa"
